services:
  - type: web
    name: syfl-ai-backend
    env: python
    region: frankfurt
    plan: free
    buildCommand: "./build.sh"
    startCommand: "uvicorn app.main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.5
      - key: MISTRAL_API_KEY
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: ALGORITHM
        value: HS256
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: 1440
      - key: DATABASE_URL
        fromDatabase:
          name: syfl-ai-db
          property: connectionString

databases:
  - name: syfl-ai-db
    plan: free
    databaseName: syfl_ai
    user: syfl_user
